apiVersion: harness.io/v1
kind: Workflow
name: # Enter a clear title
identifier: # Lowercase unique identifier using [a-zA-Z0-9_] format - e.g. harness_project_setup
owner: group:default/harness_account_all_users # Defaults to all users
# Refer to Solutions Factory documentation on various type categories. Review the naming conventions standards
# document located in the scaffolds/docs/naming-conventions.md document in this repository
type: # Required
metadata:
  description: # Provide a good description
  tags:
    - solutions-factory
    - harness
    - # Use the `hidden` tag to restrict access for only the Owners of this template
    - # Add additional tags e.g. project or pipeline
spec:
  parameters:
    - title: # Name the Input Page title
      required:
        - # List of required properties by ID
      # TODO: Enter your Harness Properties
      properties:
        # The token property needs to be in the first page of the workflow
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
    - title: Solutions Factory Connection
      properties:
        solutions_factory_details:
          title: Solutions Factory Details
          type: object
          description: |
            ---
            Harness URL : <+variable.account.solutions_factory_endpoint>

            Harness Account : <+account.identifier>

            Solutions Factory Org : <+variable.account.solutions_factory_org>

            Solutions Factory Project : <+variable.account.solutions_factory_project>
          required:
            - harness_account_url
            - harness_account_id
            - harness_org_id
            - harness_project_id
            - template_library_connector
            - template_library_repo
            - template_library_branch
            - template_library_directory # If template is at the root of the directory, then comment this out.
          properties:
            harness_account_url:
              type: string
              default: <+variable.account.solutions_factory_endpoint>
              ui:widget: hidden
            harness_account_id:
              type: string
              default: <+account.identifier>
              ui:widget: hidden
            harness_org_id:
              type: string
              default: <+variable.account.solutions_factory_org>
              ui:widget: hidden
            harness_project_id:
              type: string
              default: <+variable.account.solutions_factory_project>
              ui:widget: hidden
            template_library_connector:
              type: string
              default: <+variable.account.solutions_factory_template_library_connector>
              ui:widget: hidden
            template_library_repo:
              type: string
              default: <+variable.account.solutions_factory_template_library_repo>
              ui:widget: hidden
            template_library_branch:
              type: string
              default: main
              ui:widget: hidden
            template_library_directory:
              type: string
              default: # Provide directory path to the Terraform code in this repository e.g. harness-project
              ui:widget: hidden
        solutions_factory_opts:
          title: Solutions Factory Workflow Options
          type: object
          required:
            - repo_source
            - workspace_type
          properties:
            repo_source:
              type: string
              # Used to group by source the workspaces for bulk actions
              default: <+<+variable.account.solutions_factory_template_library_connector>.startsWith("org.Harness_Template_Library_Repo")?"official":"custom">
              ui:widget: hidden
            workspace_type:
              type: string
              # Used to group by type the workspaces for bulk actions
              default: # Provide either the directory path to the Terraform code or the custom-type for this template
              ui:widget: hidden
            is_ephemeral:
              type: string
              # Determines if the workflow will trigger a temporary workspace that is
              # deleted upon completion. Resources will be preserved
              # Must be "true" or "false" and wrapped in quotes
              default: "false"
              ui:widget: hidden
            requires_approval:
              type: string
              # Determines if the workflow will require an Approval before executing
              # Must be "true" or "false" and wrapped in quotes
              default: "false"
              ui:widget: hidden
            use_mini_factory:
              type: string
              # "When enabled, IDP workflows will default to leveraging the mini-factory to distribute workloads
              # Value must be controlled through variable
              default: <+variable.account.enable_hsf_mini_factory>
              ui:widget: hidden
  steps:
    - id: configure_workspace
      name: Configuring Harness Workspace
      action: trigger:harness-custom-pipeline
      input:
        url: ${{ parameters.solutions_factory_details.harness_account_url }}/ng/account/${{ parameters.solutions_factory_details.harness_account_id }}/all/orgs/${{ parameters.solutions_factory_details.harness_org_id }}/projects/${{ "hws_" if parameters.solutions_factory_opts.use_mini_factory=="true" else "" }}${{ parameters.organization_id if parameters.solutions_factory_opts.use_mini_factory=="true" else parameters.solutions_factory_details.harness_project_id }}/pipelines/Create_and_Manage_IACM_Workspaces/pipeline-studio?storeType=INLINE
        inputset:
          GIT_REPOSITORY_CONNECTOR: ${{ parameters.solutions_factory_details.template_library_connector }}
          GIT_REPOSITORY_NAME: ${{ parameters.solutions_factory_details.template_library_repo }}
          GIT_REPOSITORY_BRANCH: ${{ parameters.solutions_factory_details.template_library_branch }}
          GIT_REPOSITORY_PATH: ${{ parameters.solutions_factory_details.template_library_directory }}
          # The RESOURCE_NAME must be unique for each workspace created.
          RESOURCE_NAME: ${{ parameters.organization_id }}_${{ parameters.project_name|replace(" ","-")|replace("-", "_") }}
          RESOURCE_OWNER: group:default/harness_account_all_users
          # YAML of Terraform variables of type 'String' mapped to their IDP parameters
          RESOURCE_VARS:
            # harness_platform_account: ${{ parameters.solutions_factory_details.harness_account_id }}
          # YAML of Terraform variables of type 'Secret' Reference mapped to their IDP parameters
          RESOURCE_VARS_SECRETS: {}
          # YAML of Environment variables of type 'String' mapped to their IDP parameters
          RESOURCE_VARS_ENVS: {}
          # YAML of Environment variables of type 'Secret' Reference mapped to their IDP parameters
          RESOURCE_VARS_ENVS_SECRET: {}
          # Should the workspace automatically include the default Harness Connector environment variables
          INCLUDE_HARNESS_ENVS: "true"
          WORKSPACE_TAGS:
            source: ${{ parameters.solutions_factory_opts.repo_source }}
            type: ${{ parameters.solutions_factory_opts.workspace_type }}
          IS_EPHEMERAL: ${{ parameters.solutions_factory_opts.is_ephemeral }}
          REQUIRES_APPROVAL: ${{ parameters.solutions_factory_opts.requires_approval }}
        apikey: ${{ parameters.token }}
        showOutputVariables: true
  output:
    links:
      - title: Harness Workspace Configured - Execution Link
        url: ${{ steps.configure_workspace.output.PipelineUrl }}
    text:
      - title: Outputs
        content: |
          # TODO : Return outputs from Harness pipeline execution via Terraform
          # ---
          # organization_identifier: ${{ steps.configure_workspace.output['pipeline.stages.Provision.spec.execution.steps.Provision.steps.apply.output.outputVariables.organization_identifier']}}

          # project_identifier: ${{ steps.configure_workspace.output['pipeline.stages.Provision.spec.execution.steps.Provision.steps.apply.output.outputVariables.project_identifier']}}

          # project_url: ${{ steps.configure_workspace.output['pipeline.stages.Provision.spec.execution.steps.Provision.steps.apply.output.outputVariables.project_url']}}
